### ISSUE TITLE
Improved World Menu/Tool Registration

### ISSUE THREAD

**Issue by seandenigris** [dionisiydk/Calypso#105]
# World Menu
- [Enh]: Toggle option to show either Nautilus or Calypso, whichever is not currently the default
- [Enh]: Demote menu item order to allow a bit of room for user-defined items

# Tool Registration
 - [Refactor]: Use registry's `#browserTool:`

**Comment by dionisiydk** [comment]
I merged it in dev version with little fix to not reference Nautilus directly.

**Comment by dionisiydk** [comment]
in stable
