### ISSUE TITLE
Error: should not happen because of guard

### ISSUE THREAD

**Issue by apblack** [dionisiydk/Calypso#108]
I've executed `ClyBrowser beAllDefault`.  

When I use the "browse test" menu in the test runner, a new Clypso window opens with the appropriate test class selected.  But the test method is not selected (indeed, no methods or protocols are shown). Instead I get a walkback labelled `Error: should not happen because of guard`.

I don't know how to cut & paste the stack.  Here is a screenshot:
![screen shot 2017-11-17 at 13 14 34](https://user-images.githubusercontent.com/410893/32946822-5f3ef8b6-cb99-11e7-96a5-db25e21d8dca.png)

Once this has happened, any attempt to use this or any other Calypso browser is greeted with frequent walkbacks, such as
`#adaptToNumber:andSend: was sent to nil` when selecting a method

**Comment by dionisiydk** [comment]
It is clear that critic problem is still here.
So disable it with 
ClyCriticEnvironmentPlugin disableMethodGroup.
I add notes for this at readme page

**Comment by dionisiydk** [comment]
Seems latest Calypso version is fixed it. Please report it again if you would find similar problem
