### ISSUE TITLE
Compiling in a test makes Calypso raise 'Error: should not happen because of guard' when browsing methods

### ISSUE THREAD

**Issue by dupriezt** [dionisiydk/Calypso#109]
This looks like another consequence of issue #108.

I have a test compiling some code:
`testCompile
	|code|
	code := 'meth
	1+1.
	self halt.'.
	self class 
		compile: code
		classified: 'all'`

After running it, a 'should not happen because of guard' error is raised when trying to browse methods for the first time (if you browse a method and close the exception, browsing this method again will not necessarily raise another exception).

Example code available at: http://smalltalkhub.com/#!/~tdupriez/ClyCriticAnalysisBug

Stack trace:
`ClyCriticAnalysis(Object)>>error:
[ "if new process was requested from another analysis we should not reschedule it"
mainProcess notNil & (mainProcess ~~ Processor activeProcess)
	ifTrue: [ "I delay main process in order to serve new one as first. 
			If main process is current process which request aditional analysis 
			then ifTrue: case will skip it"
		mainProcess suspend.
		mainProcess isTerminated
			ifTrue: [ self error: 'should not happen because of guard' ].
		mainProcess priority: processingPriority - 1.
		mainProcess resume.
		mainProcess := newProcess ].
mainProcess ifNil: [ mainProcess := newProcess ].	"in case it is first requested process"
processes add: newProcess.
newProcess resume ] in ClyCriticAnalysis>>process: in Block: [ "if new process was requested from another analy...etc...
BlockClosure>>ensure:
[ owner := activeProcess.
aBlock
	ensure: [ owner := nil ] ] in Mutex>>critical: in Block: [ owner := activeProcess....
[ caught := true.
self wait.
blockValue := mutuallyExcludedBlock value ] in Semaphore>>critical: in Block: [ caught := true....
BlockClosure>>ensure:
Semaphore>>critical:
Mutex>>critical:
ClyCriticAnalysis>>process:
[ | newResult |
newResult := ClyCriticAnalysisResult new.
analyzedObjects register: anObject with: newResult.
analysis process: anObject.
newResult ] in [ requestedCritiques
	analysisResultFor: anObject
	ifPresent: [ :result | ^ result ]
	ifAbsent: [  ].
requestedResult := analyzedObjects
	analysisResultFor: anObject
	ifPresent: [ :result | result ]
	ifAbsent: [ | newResult |
		newResult := ClyCriticAnalysisResult new.
		analyzedObjects register: anObject with: newResult.
		analysis process: anObject.
		newResult ].
requestedCritiques register: anObject with: requestedResult copy ] in ClySystemCritic>>analyze: in Block: [ | newResult |...
IdentityDictionary(Dictionary)>>at:ifPresent:ifAbsent:
ClyCritiqueRegistry>>analysisResultFor:ifPresent:ifAbsent:
[ requestedCritiques
	analysisResultFor: anObject
	ifPresent: [ :result | ^ result ]
	ifAbsent: [  ].
requestedResult := analyzedObjects
	analysisResultFor: anObject
	ifPresent: [ :result | result ]
	ifAbsent: [ | newResult |
		newResult := ClyCriticAnalysisResult new.
		analyzedObjects register: anObject with: newResult.
		analysis process: anObject.
		newResult ].
requestedCritiques register: anObject with: requestedResult copy ] in ClySystemCritic>>analyze: in Block: [ requestedCritiques...
BlockClosure>>ensure:
[ owner := activeProcess.
aBlock
	ensure: [ owner := nil ] ] in Mutex>>critical: in Block: [ owner := activeProcess....
[ caught := true.
self wait.
blockValue := mutuallyExcludedBlock value ] in Semaphore>>critical: in Block: [ caught := true....
BlockClosure>>ensure:
Semaphore>>critical:
Mutex>>critical:
ClySystemCritic>>analyze:
ClySortedCritiques>>buildFromObject:
[ :each | self buildFromObject: each ] in ClySortedCritiques>>buildFromObjects: in Block: [ :each | self buildFromObject: each ]
IdentitySet(Set)>>do:
ClySortedCritiques>>buildFromObjects:
ClySortedCritiques>>buildFromMethods:
ClyAllItemsQuery>>fetchContent:fromMethods:
ClyMethodScope>>fetchContent:by:
ClyAllItemsQuery>>fetchContent:from:
[ items ifNotNil: [ ^ self ].
items := self defaultItems.
buildingQuery fetchContent: self from: environmentScope.
self buildIndexes.
self metadata reset.
environment resolveMetadataOf: self ] in ClySortedCritiques(ClyEnvironmentContent)>>rebuildIfNeeded in Block: [ items ifNotNil: [ ^ self ]....
BlockClosure>>ensure:`

**Comment by dionisiydk** [comment]
Seems it is fixed in latest Calypso version. Please report it again if you would find similar problem
