### ISSUE TITLE
Generate accessors produce an error

### ISSUE THREAD

**Issue by JurajKubelka** [dionisiydk/Calypso#110]
Steps to reproduce:

1. Create a class with an instance variable
2. Select the class and from its context menu choose `Generate accessors`
3. Click `OK` button

Commit f38f76e6b61c11d4109429327779d3c905976025.

![screen shot 2017-12-05 at 10 26 59](https://user-images.githubusercontent.com/465505/33609517-2f778028-d9a7-11e7-965e-3b28157551d0.png)

![screen shot 2017-12-05 at 10 26 33](https://user-images.githubusercontent.com/465505/33609524-35b8f7b4-d9a7-11e7-8111-91ee8a34dc08.png)

[stack.txt](https://github.com/dionisiydk/Calypso/files/1531261/stack.txt)

**Comment by JurajKubelka** [comment]
Apparently the issue happened in another Calypso browser. I had several opened. It happened on any method edit. Even while editing in Nautilus. I closed them all and opened new one again and it works.

**Comment by JurajKubelka** [comment]
So, the issue was in my Calypso plugin. See the associated commit. Actually, I am not sure if my change is the correct one. Maybe the issue is in `queryCurrentImageFor:`, see the commit comment.

**Comment by JurajKubelka** [comment]
I found out that it happens in that case:

```Smalltalk
(ClyClassReferences to: { ClyBrowser }) variables. "this is fine"
(ClyClassReferences to: { ClyBrowser class }) variables. "this has nil -> ClyBrowser class in variables"
```

Anyway, my plugin still fails even with the latest change. Another issue with the used cursor, that I do not understand.

**Comment by dionisiydk** [comment]
Fixed in dev version

**Comment by dionisiydk** [comment]
in stable
