### ISSUE TITLE
When clicking on overriding methods icon, Nautilus si opened

### ISSUE THREAD

**Issue by JurajKubelka** [dionisiydk/Calypso#113]
If I click on the icon:

![screen shot 2017-12-06 at 14 54 42](https://user-images.githubusercontent.com/465505/33676815-806a8d38-da95-11e7-96c9-22f3ce6fb48c.png)

It opens Nautilus instead of the default browser, Calypso.

**Comment by JurajKubelka** [comment]
Tested in Pharo 6.1

**Comment by dionisiydk** [comment]
It will be fixed when I reimplement this actions in Calypso way. Now many method decorations are done with special ClyNautilusBrowserPlugin. So override buttons are reused from Nautilus

**Comment by dionisiydk** [comment]
Done in 0.8.6
