### ISSUE TITLE
Code browser does not update when adding a breakpoint to the displayed method

### ISSUE THREAD

**Issue by dupriezt** [dionisiydk/Calypso#125]
Steps to reproduce:
- Pharo 7 image
- Load Calypso
- Open Calypso
- Open a method
- Add a breakpoint in the method (selecting a node, right-click, suggestions, Break)
- Nothing happens visually (the breakpoint and the red highlighting do not appear)

Notes: 
- Switching to another method and back to the original method makes the breakpoint appear visually
- This problem happens even after setting calypso to be the default browser

**Comment by dionisiydk** [comment]
fixed in 0.8.3

**Comment by dionisiydk** [comment]
and thank's for report
