### ISSUE TITLE
Wrong tests icon for extension methods

### ISSUE THREAD

**Issue by pavel-krivanek** [dionisiydk/Calypso#134]
Calypso has troubles with displaying of proper icons if you have a test which is an extension method of another test package.

How to reproduce:
- load [CalypsoIssueTest.st.zip](https://github.com/dionisiydk/Calypso/files/1596233/CalypsoIssueTest.st.zip)
- click on test icon next to NumberParserTest>>#testCalypsoIssue

**Comment by dionisiydk** [comment]
Done in 0.8.6
