### ISSUE TITLE
DNU when searching for a string

### ISSUE THREAD

**Issue by pavel-krivanek** [dionisiydk/Calypso#135]
DNU when searching for a text in code from a GTPlayground `RGMethodDefinition className:` in 
`ClyMethodCodeEditorTool>>#findString:asSelectorIn:`

```Instance of Text did not understand #substrings:```

A simple solution of this problem: 
```list := searchedString asString substrings: ':'.```

**Comment by dionisiydk** [comment]
Done in 0.8.6
