### ISSUE TITLE
No superclass implementation link shown for extension methods

### ISSUE THREAD

**Issue by pavel-krivanek** [dionisiydk/Calypso#141]
Having an extension methods in a superclass and subclass, in the superclass is shows that there is an implementation in a subclass with small arrow icon but in subclass it does not link an the implementation in superclass.

![pharoscreenshot 1](https://user-images.githubusercontent.com/572494/34601578-dfd54fd2-f1fc-11e7-8236-851e3a4a0ff4.png)

**Comment by dionisiydk** [comment]
Thank's.
I checked and it is fixed in upcoming version (dev branch)

**Comment by dionisiydk** [comment]
Done in 0.8.6
