### ISSUE TITLE
resetDecorators sent in postload of ConfigurationOfCalypso but this method is not available

### ISSUE THREAD

**Issue by astares** [dionisiydk/Calypso#154]
There is a method ConfigurationOfCalypso>>#initializeDecorators

initializeDecorators

	| decoratorClass |
	decoratorClass := #ClyTableDecorator 
		asClassInEnvironment: self class environment ifAbsent: [ ^self ].
	decoratorClass resetDecorators.

sending #resetDecorators

But this #resetDecorators method is not available.

**Comment by dionisiydk** [comment]
It is fine. It is here for old versions
