### ISSUE TITLE
Being on class-side should be more obvious

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#162]
In Nautilus all class-side methods were styled in **bold**, which made it very easy to see on which side I am. It would be nice to preserve this feature, or have other way to differentiate; just the checkbox is way too subtle.

**Comment by dionisiydk** [comment]
Oh, it means that users do not notice bold tabs , bold window title and there is first item "class side" in third pane which is also bold.

Problem that bold font is used for other purpose:
When superclass methods are visible the methods of selected class are bold.

**Comment by peteruhnak** [comment]
> Oh, it means that users do not notice bold tabs , bold window title and there is first item "class side" in third pane which is also bold.

Wow, I didn't notice any of that. 
* during normal workflow I don't have any reason to look at the window title; only when I am switching between different windows, and even then I look at the titles in the taskbar or on the selected context
* as for bold tabs... now that you've told me I see it... but again I don't really have much reason to look at the title of method tab, because I see the full name of the method on the first line of the source

> * there is first item "class side" in third pane which is also bold.

I don't see anything like that.

![image](https://user-images.githubusercontent.com/1276328/35403397-d885a570-01ff-11e8-9196-cf6ffc1562c3.png)

Maybe I am just too oblivious to the UI hints. But I can report how I feel about the tabs in a week or so, if I get used to it.

**Comment by peteruhnak** [comment]
Also a note... many users didn't notice Nautilus class-side bold styling until they were told so. So I am not saying Nautilus way was the best. :)

**Comment by dionisiydk** [comment]
>> there is first item "class side" in third pane which is also bold.
> I don't see anything like that.

Because today I released new version. So you need update. 
(But I am not sure how update existing version in image because Metacello script skips dependencies)

**Comment by peteruhnak** [comment]
I guess I must be really oblivious because I still managed to put methods on the wrong side...
I think the problem for me is that I am not trying actively to read the labels (because most of the time there's no point in doing that, and in the rare cases it does matter I forget).

But I think I'll just add a startup script that recompiles some styling method to put there whatever I need.
Also one more feature from nautilus got lost... when you are on instance side and there are methods on the class side, the "class" button became bold

**Comment by dionisiydk** [comment]
Just to know. Now you are using latest version where first row in third pane shows instance side or class side. Right?

**Comment by dionisiydk** [comment]
I think it is important to make good default behaviour. So maybe old bold font approach should be applied here too. I was trying to solves this problem differently. But if it does not work then we should use Nautilus approach.

**Comment by dionisiydk** [comment]
BTW, you do not need to recompile styling methods. You can implement your own table decorators in your own plugin package. 
Browse hierarchy of ClyTableDecorator to get impression on it.

In case if we would decide for old behaviour it will be implemented as new subclass

**Comment by peteruhnak** [comment]
>  Just to know. Now you are using latest version where first row in third
pane shows instance side or class side. Right?

Yes, but as I mentioned most of the time my eyes just go directly to the
methods pane... I guess this is a habit that can be unlearned, but seems
like it would be less efficient.

>  You can implement your own table decorators in your own plugin package.

Great to hear that this is extensible.

**Comment by JurajKubelka** [comment]
Just to be sure we are discussing the same version:

![screen shot 2018-02-01 at 11 05 19](https://user-images.githubusercontent.com/465505/35682607-034bd032-0740-11e8-8bfc-af5c08c9e22d.png)

So there are four places that indicates a class side. I do not like much the idea of a bold method name. It is not explicit and not clear what it does mean. I propose two changes:

- classes could say the word `class`, e.g., `ClyBrowser class` as it is common while doing `printString`. (I vote for this :-))
- class side methods could have `(class side)`. It is already used by Calypso when several classes are displayed, e.g, hierarchy. So, it is likely not a good idea.
- the method editor tab could have `methodName (class side)` (I vote for this :-))
- the editor area could have a slightly different background color (and maybe the same for protocol and method lists)

Well, I am trying to propose different solutions. I am fine with the current solution.

**Comment by dionisiydk** [comment]
Background can be good idea. But it is not so easy to support it for various themes.

For the method editor

**Comment by dionisiydk** [comment]
Background can be good idea. But it is not so easy to support it for various themes. And especial to get satisfying style for most of the people. 

For the method editor it will be useless because the long title do not show full name and the suffix will be hidden in most cases.

**Comment by peteruhnak** [comment]
@JurajKubelka you need to consider every case, e.g. here:

![image](https://user-images.githubusercontent.com/1276328/35683409-10e4f416-0764-11e8-98a9-2f5d7f1f1661.png)

* in 95% of cases the only places where I look are the red areas.
* title and class name (green) it is either in the middle of the word or not visible at all, so that's not useful
* the radio bar includes many options, so you actually have to scan with your eyes
* so the class side / instance side is the most obvious place, but if I rarely look there it's also a problem

The bottom line is: I don't want to actively check on which side I am on Every Single Time I am creating a method. I want for it to be obvious in places in which I am looking.

E.g.
* when you switch between Packages and Projects, the package/project listing changes its content
* when you switch between Flat and Hierarchy, again it is obvious from the classes listing
* when you switch between Methods and Vars, the protocols listing changes in a distinct way
* when you switch between Inst. side and Class side, there's a single word change in a long list of options in a different listing column

**Comment by dionisiydk** [comment]
Also in dark theme all this bolds are not really visible.

**Comment by dionisiydk** [comment]
As another idea:
I am going to add another checkbox into status bar to indicate and easily move method between instance and class side.
This checkbox can be red when it is class side method. Maybe it will be noticeable because it is close to editor

**Comment by JurajKubelka** [comment]
I can see that in the dark theme, a lot of things are not apparent: 

**The bold text** is not visible in the `open` method and class tab. It is obvious in the light theme. You can notice that the method name is bold in the previous attachment.

**Radio buttons** are confusing. There should be just one color for a selected button and background color for deselected buttons. Well, observing it again, maybe there is just one color... but notice that selected tab has dark color, and selected radio buttons have light color. This is confusing to me.

@peteruhnak: So, maybe try for a while the light theme to notice the difference. Maybe the dark theme should be improved first. For example, if the bold text is hard to notice (and it is!) then, having bold method names is not that useful.

@dionisiydk: Let's try your idea. I suspect it is not going to work for @peteruhnak.

@dionisiydk: And what about adding `class` suffix in the class table? Maybe a bit lighter color than the normal text color.

**Comment by dionisiydk** [comment]
I will try class suffix for classes. It can work. And maybe bold font for them instead of bold methods.

**Comment by dionisiydk** [comment]
At the end I just apply Nautilus logic. 
So protocols and methods are bold when class side is active.
