### ISSUE TITLE
The currently edited class should be the first option when overriding methods

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#163]
![image](https://user-images.githubusercontent.com/1276328/35399618-f28a7302-01f4-11e8-8643-9fe7398fdd70.png)

my rationale: I have the subclass selected, I would expect that most code changes will be done in that method; also I expect that one more often overrides abstract methods than changes the abstract method itself.

**Comment by dionisiydk** [comment]
I did it even better. There was no way to do it like that in past.
Now the dialog shows class hierarchy. 
![calypsowhereinstallmethod](https://user-images.githubusercontent.com/8149664/35575883-e12b1d22-05dd-11e8-843b-8b087d0100e4.png)
And traits are also taken into account :
![calypsowhereinstallnewmethodtraitcase](https://user-images.githubusercontent.com/8149664/35575884-e1683892-05dd-11e8-940f-8cd47f4ac085.png)
The hierarchy is based on method visibility hierarchy when you expand first item in third pane.
If you will inverse this hierarchy in settings it will affect this dialog too. I think it is consistent.

It is now in dev version

**Comment by dionisiydk** [comment]
in 0.8.12
