### ISSUE TITLE
Overridden methods icon does not work on the class side

### ISSUE THREAD

**Issue by JurajKubelka** [dionisiydk/Calypso#169]
Steps to reproduce:
1. create a class and switch to the class side,
2. add a method `package ^ super package`,
3. click on the overridden methods icon next to the `package` name.

The message browser will be empty, there should be `ClassDescription class >> #package`

**Comment by dionisiydk** [comment]
It works for me. 
Are you sure that you are on the latest version? 
Do you see "inherited method" group in third pane? (it should not be there)

**Comment by JurajKubelka** [comment]
I have tried on a fresh Pharo images and it works in Pharo 7, but it does not work in Pharo 6.1 (Pharo 6.0 Latest update: #60528).

**Comment by dionisiydk** [comment]
You are right. Traits were not taken into account for this command. It was based on simple superclass scope instead of general inherited scope.
Fixed in dev

**Comment by dionisiydk** [comment]
So in Calypso TClassDescription will be shown

**Comment by dionisiydk** [comment]
in 0.9.0
