### ISSUE TITLE
in senders browser ctrl+w closes the content of the current tab, instead of the tab

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#174]
E.g. I have senders window that has multiple tabs, then I press ctrl+w to close the current one, but instead only the content of the tab disappears, but the tab remains (with empty content):

![image](https://user-images.githubusercontent.com/1276328/35623775-12594112-068d-11e8-8de7-e6a34dd6133f.png)

pressing ctrl+w again closes everything

**Expected behavior:**
ctrl+w closes the active tab (and only if I am closing the last tab it should delete the entire window)

**Comment by dionisiydk** [comment]
I also noticed it but very rarely. 
So I do not have reproducible scenario. In most cases cmd+w closes tab correctly

**Comment by peteruhnak** [comment]
For me it was so far 100% of the time, e.g.

1. open Morph in Calypso
2. click on "Class refs." (in Calypso)
3. click on "Implementors" (in References browser)
4. press ctrl+w

maybe it is Windows specific? (although I don't see why platform should
matter)

**Comment by dionisiydk** [comment]
I found how to reproduce.
In multi tabbed window focus the editor. So text editor will be active. Now close this editor tab using cross icon. And now press multiple cmd+w without switching any focus.

**Comment by dionisiydk** [comment]
In that case the command which implements browser close logic is not called. And some primitive window behaviour is evaluated

**Comment by dionisiydk** [comment]
If Windows platform affects how focus is work then it can affect this behaviour too
