### ISSUE TITLE
combine icon and protocol name for method

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#175]
It would be nice to be able to click not just on the icon (which is small, and hard to recognize), but also on the protocol name (similar to how you can click both on the extension checkbox, as well as the _extension_ word).

![image](https://user-images.githubusercontent.com/1276328/35625077-4c713158-0691-11e8-9c3f-ba0fb0b98c28.png)

**Comment by dionisiydk** [comment]
in 0.9.0
