### ISSUE TITLE
bold methods because of traits

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#177]
> When superclass methods are visible the methods of selected class are bold.

Apparently when a class implements a trait, then the trait is considered a superclass. This seems superfluous, because trait methods are already distinguished by an icon.

**Comment by dionisiydk** [comment]
It is just general behaviour for method visibility. It is not bound to superclass or trait.
Also you can select superclass together with trait methods. 

Idea that bold methods are ones which are explicitly defined by selected class.

Maybe we should just remove this bold highlighting in general. And only use it for class side methods indication

**Comment by dionisiydk** [comment]
I disable this behaviour in 0.9.0
