### ISSUE TITLE
CMD (+ SHIFT) + Mouse click opens a new Method Browser window instead of a new tab

### ISSUE THREAD

**Issue by JurajKubelka** [dionisiydk/Calypso#178]
Steps to reproduce:

1. Open a method browser, e.g., displaying implementors.
2. Browse a method definition that includes message calls.
3. On macOS do CMD+click on any message call inside of the displayed messaged.

It opens a new window. If you select the message call and do CMD+M, it opens new tab in the same window. The CMD+click and CMD+SHIFT+click works on methods, variables, and classes.

**Comment by dionisiydk** [comment]
It's because cmd+click is not implemented by Calypso or Commander. It works the old way and do not intercepted by browser.

It needs to be implemented which will brings many interesting features

**Comment by dionisiydk** [comment]
it was easy to fix: I already have ClyTextEditor where I override navigation methods from default smalltalk editor.
So it is in dev branch now

**Comment by dionisiydk** [comment]
And thank's for report. 
Actually I didn't know about this feature

**Comment by JurajKubelka** [comment]
That's great :-) Thanks!
What interesting features it will bring? I am curious :-)

**Comment by dionisiydk** [comment]
Nothing :)
I just thought about click/doubleclick activation strategy which needs to be added to Commander.
It will allow to configure commands to be activated by click/doubleclick on particular class/method/package

**Comment by dionisiydk** [comment]
But in this issue I just continue hook text editor in its own way.
So text editor is still do not driven by Commander

**Comment by dionisiydk** [comment]
in 0.9.0
