### ISSUE TITLE
Add better search for methods

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#180]
In Nautilus one can open a search dialog with ctrl+f+(c for classes, t for protocols, m for methods).

There is currently something (that is also in Nautilus) where I can just start typing and it will search, but the full dialog allowed: 

* full text search (so I can type just part of the name starting anywhere)
* filtering (so I see only relevant results)

I don't know how useful it is for protocols and packages (I've never used it there), but I heavily use it for methods and classes (the search for classes apparently still works)

**Comment by dionisiydk** [comment]
in 0.9.0. 
cmd+f when methods pane is active
