### ISSUE TITLE
Opening `Interval` class raises error

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#181]
0. calypso default browser
1. open spotter, type in Interval, press enter

![image](https://user-images.githubusercontent.com/1276328/35701632-df965778-0796-11e8-8ad2-52f821536302.png)

The same issue happens when you go to `Collections-Sequenceable` package and click on `Interval` class

**Comment by peteruhnak** [comment]
This seems also the same, in different situation:

1. open String
2. select accessing protocol
3. start scrolling methods pane

![image](https://user-images.githubusercontent.com/1276328/35721798-0bbf8ac4-07f4-11e8-9978-949382bdcfee.png)

* the error is from halo click > debug drawing error
* step no. 2 can be skipped but more scrolling is needed (I guess until one runs into method from trait?)

**Comment by dionisiydk** [comment]
fixes in dev version.
Thank's for the report. It worked in Pharo 7 where #isAbstract is defined on Behavior

**Comment by peteruhnak** [comment]
Can confirm that this is fixed in dev. Thanks!
