### ISSUE TITLE
shortcut activation for ClySwitchToClassSideCommand

### ISSUE THREAD

**Issue by JurajKubelka** [dionisiydk/Calypso#182]
I wanted to make shortcut combinations for the actions that are in the middle toolbar. How can I do it? 

I tried: 

```Smalltalk
ClySwitchToClassSideCommand class >> fullBrowserShortcutActivation
	<classAnnotation>
	^ CmdShortcutCommandActivation by: $g meta , $c meta for: ClyMethodContextOfFullBrowser
```

But it likely does not work, right? My idea was having

CMD+G (go), CMD+c --> switch to class side
CMD+G (go), CMD+i --> switch to instance side
CMD+G (go), CMD+f --> switch to flat
CMD+G (go), CMD+h --> switch to hierarchy
CMD+G (go), CMD+m --> switch to methods
CMD+G (go), CMD+v --> switch to variables

Maybe it could be CMD+S (switch) instead of CMD+G (go).

As for now the switchers are in pairs, we might consider another command that switch packages/projects, instance/class side, methods/variables.

What do you think?

**Comment by dionisiydk** [comment]
With your example it will work when focus is in the method pane.
To make it works everywhere you can use ClyFullBrowserContext.

BTW cmd+s is already in use to commit packages.

**Comment by JurajKubelka** [comment]
Thanks! it works. Well, it does not work when I am in a text editor. Is there way it can work meanwhile I am in the text editor? Or can I leave the text editor using a shortcut? So I do not have to do an extra click to be able to use the shortcuts...

Where is the CMD+S defined? I can see `Commit` in the package context menu, but the short cut is not displayed.

![captura de pantalla 2018-02-02 a la s 16 39 34 1](https://user-images.githubusercontent.com/465505/35751526-b0e98b10-0837-11e8-8956-efccdc36dd1f.png)

**Comment by dionisiydk** [comment]
For text editor add another activation in context ClyTextEditorContext

**Comment by dionisiydk** [comment]
Probably there is a problem with displaying shortcuts in menu in some cases

**Comment by JurajKubelka** [comment]
Having:

```Smalltalk
ClySwitchToClassSideCommand class >>  textEditorShortcutActivation
	<classAnnotation>
	^ CmdShortcutCommandActivation by: $j meta , $c meta for: ClyTextEditorContext
```

Does not work as `ClySourceCodeContext` does not understand `hasSelectedItems`. So, I cannot use the same command in both, browser and source code, contexts.

**Comment by dionisiydk** [comment]
I fixed it in dev version:
This command do not need selected items. Selected class was just desired context where we want this command in toolbar. So I removed canBeExecuted method and replace context with "ClyClass asCalypsoItemContext"

**Comment by dionisiydk** [comment]
in 0.9.0
