### ISSUE TITLE
Rename and Remove should be consistent

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#185]
The placement of Rename and Remove in the context menu should be consistent.

I think the way it is done for Class and Method is ideal (Remove at the very end, Rename at the top)

package
![image](https://user-images.githubusercontent.com/1276328/36071761-0ed2f742-0f14-11e8-8a82-12ed64fc59dd.png)

class
![image](https://user-images.githubusercontent.com/1276328/36071764-16099b24-0f14-11e8-9ec9-6ccdf8f70fa2.png)

protocol
![image](https://user-images.githubusercontent.com/1276328/36071770-21af052c-0f14-11e8-9b85-098f18565ab6.png)

method
![image](https://user-images.githubusercontent.com/1276328/36071772-2876ce76-0f14-11e8-8737-e35903feac52.png)

**Comment by dionisiydk** [comment]
Done in 0.9.0
