### ISSUE TITLE
Find Class isn't regex

### ISSUE THREAD

**Issue by akgrant43** [dionisiydk/Calypso#197]
When searching for a class in Nautilus the Find Class dialog input is a regex allowing for terms such as "^File" to find all classes that begin with "File".

It would be great to have the same functionality in Calypso.

Thanks,
Alistair

**Comment by dionisiydk** [comment]
Is it same like in package filter? (in full browser)

**Comment by akgrant43** [comment]
Hi Denis,

> Is it same like in package filter? (in full browser)

I'm not sure I understand what you're asking, sorry.

The "Find Package..." dialog in the Nautilus browser is also a regex search, i.e. entering "file" will return "DeprecatedFileStream" and "FileSystem-Core" (amongst other classes), while "^file" will only return packages beginning with "File", e.g. "FileSystem-Core".

Please let me know if I've misunderstood your question.

Thanks,
Alistair

**Comment by dionisiydk** [comment]
I mean there is filter field under package view in full browser (below first table with packages). It works using regex. 

So I reused it for search dialog. It will be in next version (now it's in dev branch)

**Comment by dionisiydk** [comment]
I am closing issues when I release version which covers them

**Comment by akgrant43** [comment]
> I am closing issues when I release version which covers them

Great.  I'm looking forward to the update :-)

**Comment by dionisiydk** [comment]
Done in Calypso 0.10.2
