### ISSUE TITLE
It is not possible to rename a package extension category

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Calypso#198]
Version: 0.10.1

Pharo : 7

I did a right click on a protocol of package extension and I expected to be able to rename this protocol, but the option was not present.

**Comment by dionisiydk** [comment]
Renaming extending package means classifying all extension methods.
So currently you should explicitly execute "Classify methods" command from menu. Or use status bar checkbox "extension"

**Comment by dionisiydk** [comment]
It is important that in Calypso package and protocol are independent from each other. At least Calypso tries to show it that way in UI. 
In future it will be true in general: methods can be in any protocol and in same time it can be extension.

**Comment by jecisc** [comment]
But "Classify methods" is only on the methods menu. Don't you think it should be possible also from the protocol pane?

**Comment by dionisiydk** [comment]
I see what you mean.
I will add two commands for extending package:
- move to protocol
- move to package

**Comment by jecisc** [comment]
Cool! Thank you. I saw that what I wanted to do was possible via the method pane but less intuitive for people coming from Nautilus.

**Comment by dionisiydk** [comment]
But I wonder, is it really common for you to move all extension methods to some protocol? Or to move all extension methods to another package?
Because I not remember that I was needed it anytime. And that's why these commands not exist

**Comment by jecisc** [comment]
When I clean some projects where UI and Model are not well separated, I often need to move extension methods relative to the UI from the model package to the UI package. In that case I might need this option.

**Comment by jecisc** [comment]
That's my use case but maybe it is too specific.

**Comment by dionisiydk** [comment]
I added commands in dev branch. I will close issue after release

**Comment by dionisiydk** [comment]
Done in Calypso 0.10.2
