### ISSUE TITLE
Implement inspector tab on class side variables 

### ISSUE THREAD

**Issue by dionisiydk** [dionisiydk/Calypso#20]
Class side variables are usually initialised with some values. It would be nice to see inspector for them directly in browser in extra tool tab

**Comment by dionisiydk** [comment]
New tool should be shown as tab when user select class side variable

**Comment by bencoman** [comment]
nice idea.

**Comment by dionisiydk** [comment]
In 0.10.3 there is inspect menu item and cmd+i shortcut for variables pane. So I think extra tab is not needed
