### ISSUE TITLE
Missing "Compare two methods" functionality in Calypso

### ISSUE THREAD

**Issue by astares** [dionisiydk/Calypso#204]
In Nautilus it is possible to select two methods in the method pane
and select "Compare two methods" from the context menu.

This very useful (for instance to check for two methods having the same implementation
or compare two versions in a ConfigurationOf... and many others)

This functionality is missing in Calypso and should be added

**Comment by astares** [comment]
https://pharo.fogbugz.com/f/cases/21497

**Comment by dionisiydk** [comment]
I wonder, did you see that method diff is automatically opened when you select two methods? It is in the last tab

**Comment by astares** [comment]
No, I did not see it. Only after you mentioned it now. So functionality is there - but it is not obvious and user friendly IMHO. 

Maybe this tab should be activated/brought to front and attention when two methods are selected...

**Comment by dionisiydk** [comment]
It was before like that before last release. 
It was always annoying to see diff every time you select few methods to perform some group operation (remove, classify). So I disabled auto selection.

Generally I agree that such tools should be opened manually. But there is no such mechanism now. So it is not in priority.
First, manualy opened tabs should be implemented.

**Comment by dionisiydk** [comment]
I think this issue can be closed.
The feature is here but not in Nautilus way.

**Comment by astares** [comment]
OK
