### ISSUE TITLE
Generation of class variables accessors

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Calypso#215]
I tried to add a class variable to an object then I wanted to generate the accessors via a right click on the class name -> "generate accessors" .

But this opens a window with no possibility to generate the class accessors. 

Is it possible to do this in the current version of Calypso?

**Comment by dionisiydk** [comment]
Switch to variables view and expand class variables. Then select variable and there will be item in menu.

**Comment by dionisiydk** [comment]
But I found it does not work. I will fix it

**Comment by jecisc** [comment]
Ok thank you. I'll have to take the habit of Calypso. But it will be slow since I can only use it at home.

**Comment by dionisiydk** [comment]
in 0.11.0
