### ISSUE TITLE
Too many protocols on some classes

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Calypso#219]
I opened Calypso on the class ThreePhaseButtonMorph and I checked the class side checkbox.

In the protocol pane, I see a lot of protocols, but only one has methods inside. I don't know from where the other protocols come. 

![image](https://user-images.githubusercontent.com/9519971/37124247-c32ce16a-2267-11e8-8854-56d2b88aa798.png)

**Comment by dionisiydk** [comment]
It is an issue of new Traits implementation https://pharo.fogbugz.com/f/cases/21517/New-traits-copy-all-class-side-methods-of-TraitedClass-to-all-subclasses-of-trait-users.
You can check in Pharo 6 it works fine

**Comment by dionisiydk** [comment]
And thank's for this finding. It is critical bug. It even leads to grown image (it's around 6 mb more now)
