### ISSUE TITLE
Protocol "class initialization" should have the yellow initialization icon too

### ISSUE THREAD

**Issue by astares** [dionisiydk/Calypso#223]
FEATURE REQUEST:

Can you please adopt ClyTaggedMethodGroup>>decorateTableCell:of:

using the following array:
    (#('initial' 'class initial' 'releaz' 'releas' 'finali') 

so that also the class side "class initialization" protocol has the yellow initial icon

Thanks in advance!

**Comment by dionisiydk** [comment]
in 0.11.0

**Comment by astares** [comment]
Thanks!
