### ISSUE TITLE
Opening classes with class>>isAbstract leads to an error

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#230]
Opening class-side when `isAbstract` is implemented leads to an error.

1. open `TonelReader`
2. click on class-side

![image](https://user-images.githubusercontent.com/1276328/38200095-4b24a5f0-3693-11e8-9fd9-c351a8047dfd.png)

**Comment by dionisiydk** [comment]
Can't reproduce. What image are you using?

**Comment by dionisiydk** [comment]
I found problem. Thanks

**Comment by peteruhnak** [comment]
Sorry, Pharo6.

**Comment by dionisiydk** [comment]
Done in 0.11.1
