### ISSUE TITLE
Deleting class that had method selected leads to OutOfBounds error

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#231]
(Pharo 6)
Sometimes when I delete a class and then select some other class I run into this

![image](https://user-images.githubusercontent.com/1276328/38208751-66a57efc-36b2-11e8-9c38-3f437a2e4c04.png)

I don't know how to consistently reproduce it, although I experience it quite often.
Also worth noting that if there was a method selected of the given class, then it remains "opened" even after the class was deleted... so I guess it somehow didn't properly deselect it before removing it.

**Comment by dionisiydk** [comment]
Fixed in dev
