### ISSUE TITLE
Calypso references-to not working for class variables

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#235]
In Pharo 60540, using Nautilus to view the Delay class definition,
selecting class variable 'Scheduler' > right-click > Code search > references to it
produces 13 results.

In Pharo-7.0+alpha.build.762.sha.0e0fe47c5 doing the same with Calypso
produces 0 results.  It still works with Nautilus.

**Comment by dionisiydk** [comment]
Thank's. I fixed in dev.

**Comment by dionisiydk** [comment]
Done in 0.11.1
