### ISSUE TITLE
Swap page up/page down and home/end

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#244]
Related to the filter functionality

![image](https://user-images.githubusercontent.com/1276328/38862294-d33d5278-4234-11e8-87ae-897dd3d91ab2.png)

Home/End keys are typically used to jump to beginning/end of a line, while page up/page down is for vertical jumping/scrolling.

However in calypso they swapped: page up/down is used for jumping to start/end of the filtered text, whilst home/end is used to jump to the first/last selected item

**Comment by dionisiydk** [comment]
I think it is general FastTable problem. 
Can you check it in fast table examples? (I don't have such keys on my keyboard)

**Comment by peteruhnak** [comment]
I've created issue for FastTable https://pharo.fogbugz.com/f/cases/21720/FastTable-should-swap-home-end-and-page-up-page-down . It seems that it depends on OS a bit.

**Comment by dionisiydk** [comment]
So I close this one because it is not related
