### ISSUE TITLE
Pressing home/end on an empty selection triggers OutOfBounds

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#245]
*To reproduce:*

1. in either package or class filter enter text that will result in empty list
2. press home or end key to jump to an item in the selection

![image](https://user-images.githubusercontent.com/1276328/38862454-4561af20-4235-11e8-87df-6e165dc03bb8.png)

related: #244

**Comment by dionisiydk** [comment]
Got it. Thank's.
I fixed it in dev. But it is problem of fast table. Now all users should take care about it

**Comment by peteruhnak** [comment]
I guess? But if I look at `FTExamples class>>exampleTreeWithRootFilter` it doesn't produce any OutOfBounds when pressing home/end on empty selection.

**Comment by dionisiydk** [comment]
It's because these examples do not manage selection.

**Comment by dionisiydk** [comment]
in 0.11.2
