### ISSUE TITLE
Trying to browse class from code triggers DNU

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#246]
Trying to browse a class fails from code on ClyTextEditor DNU #findClassFromAST

I guess this was broken by this commit? https://github.com/dionisiydk/Calypso/commit/c98f0a301cb35b52130588e3b6d926e12e97639d

(tested on Linux, Pharo 6.1)

![image](https://user-images.githubusercontent.com/1276328/38935787-80072bce-431f-11e8-8f9e-0b91d127cfab.png)

**Comment by dionisiydk** [comment]
Shit. When I fixed case #239 I reuse code from SmalltalkTextEditor. But it is not available in Pharo 6

**Comment by dionisiydk** [comment]
fix in dev

**Comment by dionisiydk** [comment]
in 0.11.2
