### ISSUE TITLE
SharedPool variables menu is not working

### ISSUE THREAD

**Issue by peteruhnak** [dionisiydk/Calypso#253]
Trying to right-click on a selected pool variable results in error.
![image](https://user-images.githubusercontent.com/1276328/39096430-48147c06-4650-11e8-8d51-3fde2ad6d1e0.png)

![image](https://user-images.githubusercontent.com/1276328/39096431-56395f04-4650-11e8-8f41-fdc6686b2903.png)

It would be nice if the menu offered an option to navigate to the variable assignment/definition (this one is defined in `AthensCairoDefs class>>initialize_cairo_font_slant_t`.

In fact I don't know how to achieve this even with regular variables; Nautilus had "class context menu" > Analyze > Inst Var Assignments

**Comment by dionisiydk** [comment]
It's already fixed in 0.11.1.
So you need update.
For assignments there is "writers" item in "source code" menu (old suggestions).
And these queries are available in "Vars browser mode" from context menu (where variables are shown instead of protocols)

**Comment by dionisiydk** [comment]
It's already fixed in 0.11.1.
So you need update.
For assignments you have now "writers" item in "source code" menu (old suggestions)

**Comment by dionisiydk** [comment]
And there is command "Browser" in source code menu. It opens class where given variable is defined
