### ISSUE TITLE
waitReadyMorphFor: missing

### ISSUE THREAD

**Issue by HeSe** [dionisiydk/Calypso#26]
Hi! 
I just had a look into this package and what I saw was a great upgrade on the Systems Browser! Great!
However, I had trouble to load the code into the most current Pharo6 image.

The mothod "waitReadyMorphFor:" is missing.... 

One notice on the side. It would be a great and an additional improvement if one would be presented the content of Class Variables in the 4th column (methods list view) upon selection in the 3rd column (categories list view). Like an inspector view...

**Comment by dionisiydk** [comment]
Hi.
I guess you skip loading instructions on my blog. Now Calypso requires few fixes which are not yet integrated in Pharo6.

I update readme here with script to load all them together. 

I will close this issue when they will be integrated

**Comment by dionisiydk** [comment]
About you idea on class vars. I also thought about it, issue here #20 . 
To me it should be as tool-inspector on extra tab when we select class var. 
I prefer 4-th column to always show related methods and not something else.

**Comment by dionisiydk** [comment]
All required fixes are integrated in Pharo 6. So I close issue
