### ISSUE TITLE
Implement add new class command

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#27]
With ConfigurationOfCalypso-DenisKudryashov.8
in packages pane, right-click > Add New Package "AAAA"
in empty classes pane, right-click > Add New Class
==> Instance of ClyStandardBrowserCommands did not understand #addNewClass

**Comment by dionisiydk** [comment]
Yes. First time I just describe commands which I want. And probably I forgot to implement all of them :)

**Comment by dionisiydk** [comment]
So now it is just missing command

**Comment by dionisiydk** [comment]
In v0.8.5:
"New subclass" menu item of selected class. It just requests new class name, then it creates class and switches the browser to it. So the new class definition become selected where variables can be added.
I think it is enough behaviour. 
If you want something different, please, open new issue with details
