### ISSUE TITLE
Multi-select should accumulate individual items, not just range

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#28]
Really nice idea to multi-select.  Still need to find its workflow in practice, but its a constraint to only multi-select a range with <Shift> key.  Accumulating individual selection via typical <Ctrl> modifier would help.

**Comment by dionisiydk** [comment]
It needs to be improved at FastTable. But it is actually work now: try cmd+click on any item. It will add selected element to selection. 
But it is not shown nicely and context menu is always appear and confuse.
Maybe it is issue for Pharo? and we could close this one?

**Comment by dionisiydk** [comment]
And range selection with shift+click working well

**Comment by bencoman** [comment]
> It needs to be improved at FastTable. Maybe it is issue for Pharo?  and we could close this one?
okay.

> But it is actually work now: try cmd+click on any item. It will add selected element to selection.
This is not working using either Ctrl or Alt in Linux.

**Comment by dionisiydk** [comment]
It is also problem of FastTable and maybe even VM.
I checked it only on Mac
