### ISSUE TITLE
Accumulate individual multi-selects using <Ctrl> modifier 

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#32]
Really nice idea to multi-select.  Still need to trial its practical effect on my workflow, but it would help to be able to accumulate individual selections via typical <Ctrl> modifier, rather than just range select with <Shift> modifier.

**Comment by dionisiydk** [comment]
Ben, how it is related to #28 ? And do you read my comment?

**Comment by bencoman** [comment]
argh! how did I do that.  Closing as a dup of #28.
