### ISSUE TITLE
Protocol pane scroll bar doesn't position properly when items added

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#34]
In 60334,
1.  ClySystemBrowser open.
2. Select Collections-Streams > PositionableStream
3. Select inherited methods > Object
4. Scroll down to "extensions" at the bottom of list and expand it
==> scroll bar resizes okay, but it doesn't reposition. So it looks like you are already at the bottom of the list, when the bottom of list has moved with added items.  

Is this maybe a FastTable issue?

**Comment by dionisiydk** [comment]
Yes, it is only fast table issue

**Comment by dionisiydk** [comment]
Now extensions is not at bottom. So I am not sure that it is still relevant. Also there was many improvements in FastTable. 
I think I close this issue
