### ISSUE TITLE
In protocol pane, some extensions appear twice

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#35]
In 60334,
1. ClySystemBrowser open.
2. Select Collections-Streams > PositionableStream
3. Select inherited methods > Object
4. Expand extensions
==> Epicea appears twice.

**Comment by dionisiydk** [comment]
Nice catch

**Comment by dionisiydk** [comment]
Ok. It is not related to inherited methods.
Just browse Object and you will see two Epicea.
Problem that Calypso try to show extending packages and not protocol. And sometimes extension protocol has name like "packageName-extraTag"

**Comment by dionisiydk** [comment]
And done!
