### ISSUE TITLE
Extension protocols not highlighted when method selected

### ISSUE THREAD

**Issue by bencoman** [dionisiydk/Calypso#38]
>> Selecting... Collections-Streams > ReadWriteStream > inherited methods
>>   asBinaryOrTextStream(PositionableStream) is shown normal
>>   asZLibReadStream(PositionableStream) is shown grey
>> Can you explain?
>
> It's easy. Class extension is shown with grey and #asZLibReadStream is from
> Compression package.
> Actually this logic is a bit different. If method not belongs to selected
> package (from package view) then it will be shown with grey. 
> It is current logic of Nautilus.

Okay.  That should have been obvious.  So in trying to work out why my mind faltered, I think it may be because Nautlius provides visual feedback by light-highlighting the extension package (i.e. Compression) where Calypso does not - it only highlights real protocols.

**Comment by dionisiydk** [comment]
includesMethod: methods is needs to be implemented on ClyExtendedMethodGroup

**Comment by dionisiydk** [comment]
Done
