### ISSUE TITLE
Some UI elements are not Dark Theme friendly

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Calypso#39]
See: http://puu.sh/tfkUB/ce1c202363.png

The "inherited methods" label and also the color of the unselected tabs. 
It's maybe not a problem of Calypso but I don't have the time to investigate more.

**Comment by dionisiydk** [comment]
Yes, I saw it. 
Do you know how themes is managed? What the way to made UI respecting theme?

**Comment by jecisc** [comment]
Yes I know. I will explain as soon as I come back to my computer.

**Comment by jecisc** [comment]
Ok so UI stuff. 

In Pharo there is a UITheme class that is subclassed by different themes. It store a list of theme related stuff as colors.

You can get the current theme via `Smalltalk ui theme`.

Some objects in Pharo can directly implement the #theme method as morphs. When something is theme related it should use this theme class.

Some morphs for example can let the user customize their color, but they will have a default color that can be `self theme borderColor`.

Another thing, when we change the theme of Pharo, morphs use the #themeChanged method (usually extensions methods from Polymorph-widgets package) to know how they should update to match the new theme.

**Comment by dionisiydk** [comment]
Now it is better I use in some places theme background colour. 
But marking some groups with blue is not respect theme yet

**Comment by dionisiydk** [comment]
Fixed
