### ISSUE TITLE
Toolbar: The ui should tell which radio are linked

### ISSUE THREAD

**Issue by jecisc** [dionisiydk/Calypso#40]
Trying to use Calypso I see that "Flat classes" and "Hier." are linked together. But there is no indication that they are not linked to "Inst. side". 

The UI should give this information. Maybe with separators?

**Comment by dionisiydk** [comment]
Yes, I feel same and also thought about separators like in menus. I will try it.
And here is also question how to respect theme for new UI elements

**Comment by dionisiydk** [comment]
Done with separators
