### ISSUE TITLE
Installation from Gofer asks to resolve dependencies in ClassTagAnnouncement and FTSubstringFilter

### ISSUE THREAD

**Issue by offray** [dionisiydk/Calypso#41]
While installing from Gofer I got this warnings:

```
This package depends on the following classes:
  ClassTagAnnouncement
You must resolve these dependencies before you will be able to load these definitions: 
  ClassTagAnnouncement>>#fixEnvironmentContent:
```
```
This package depends on the following classes:
  FTSubstringFilter
You must resolve these dependencies before you will be able to load these definitions: 
  FTSubstringFilter>>#asClyItemFilter
```
and, of course, launching doesn't work without those dependencies installed. I'm working on Pharo 5. (Latest update: #50761)

**Comment by dionisiydk** [comment]
Calypso is not supposed to work with Pharo5. Many fixes was done in Pharo6 which are mandatory for Calypso.
I just check latest Pharo6: loading stable version works without problem. 
Dev version requires extra fix https://pharo.fogbugz.com/f/cases/19521/localMethods-should-be-moved-to-TBehavior-where-localSelectors-methods-are-defined

**Comment by offray** [comment]
Thanks Denis. I will not move yet to Pharo 6. But once I have done, I 
will test Calypso.

Cheers,

Offray
