### ISSUE TITLE
Issues with format as you read

### ISSUE THREAD

**Issue by rcpacheco** [dionisiydk/Calypso#52]
In the Class Editor there is no check for Format as you read, only when you edit methods. Is that correct?
Also, when you paste some code in the method editor,  even if you have this check, it is saved with the original format, and not properly formated. What I do to take advantage of this functionality is, after pasting some code, I uncheck and check this option and only then the code is formated. Is it possible to format it prior saving if the option is enabled or at least format all the text if you key something after pasting, like a new line?
Sometimes you give format to the text, following the procedure I mentioned above, and the resulting format leaves an empty line between the comment and the code; you save it, but later, when you check the content of the method, there is no empty line between the comment and the code. Is that correct?

**Comment by dionisiydk** [comment]
For first question: yes. Do you think it is needed for class definition?

For the rest: is this behaviour same in Nautilus? because I just reused existing tools here

**Comment by rcpacheco** [comment]
Hi Denis. 

First response: I think given the fact that a class definitions is small it may be OK to leave the checkbox out, as long as the format is automatically applied to the definition upon save. That is the current behavior. So, no problem with that.

Second response: 
In both Calypso & Nautilus, if you have checked the option Format as you read, when you paste code aligned all to the left and then save, it is saved as it is with no format. In Nautilius, if you select the name of the method and you still have the check selected, it is displayed with format. If then you unselect the check it is displayed aligned to the left as original. Nevertheless, Calypso  displays the code without format even if the check is selected. To force Calypso to format I have to uncheck and check again the option.

**Comment by dionisiydk** [comment]
I fixed it in dev version.
Now Calypso reformats saved code if option is enabled

**Comment by dionisiydk** [comment]
If you ok with it then close issue please

**Comment by rcpacheco** [comment]
Sorry to ask such a basic question, but how can I load the dev version to an image that already has the master version?
I searched for the syntax of Gofer to update to a different branch, but did not find any example.

Thanks a lot.

**Comment by dionisiydk** [comment]
I use following script to update:

Gofer it
smalltalkhubUser: 'Pharo' project: 'Calypso';
configuration;
loadDevelopment.

I hope it works. I doubt because I modify deeply baseline and it is
possible that something will break during loading in old Calypso version.
It should not, but...

2017-04-18 18:17 GMT+02:00 Ricardo Pacheco <notifications@github.com>:
