### ISSUE TITLE
ClyHierarchicallySortedClasses do not scale

### ISSUE THREAD

**Issue by DraagrenKirneh** [dionisiydk/Calypso#58]
See difference in time for ClyHierarchicallySortedClasses and SortHierarchically 
```Smalltalk
[ 
ClyHierarchicallySortedClasses new
	items: (OrderedCollection new);
	buildFromClasses: Smalltalk allClasses;
	items
] timeToRun. "0:00:00:32.121"

[ 
SortHierarchically sortClasses: Smalltalk allClasses		
] timeToRun  "0:00:00:00.046"
```

**Comment by dionisiydk** [comment]
Try to do it with "Smalltalk allClasses asIdentitySet" - result will be comparable.
What exactly you are trying to measure? I guess this test is side note?

**Comment by dionisiydk** [comment]
Now with new hierarchy implementation it is definitely not an issue anymore
