### ISSUE TITLE
Rework naming conventions

### ISSUE THREAD

**Issue by Phantasus** [dionisiydk/Calypso#62]
Hi,

currently I tried as an interested person in pharo and calypso to look at its source code
and tried to understand it. I have currently some annoying issues when doing that:

1. The package names, class names and also the method names are just too long. I use at home an old Flatscreen with a resolution of 1024x768 screen and the names are barely readable:
![image](https://user-images.githubusercontent.com/1078087/27997202-5b7a297e-64f3-11e7-9621-b94774e0c817.png)

2. I hope the target of naming each package, class or method this way was to make it understandable,
but it doesn't. What should names like "ClyInheritedMethodGroupHierarchyBuilder" really mean? Just to give a little insight in my perceived frustration with such a name from my point of view of thinking: "Ok,
it's some kind of builder I guess, it should hopefully build the "InheritedMethodGroupHierarchy" thingy,
whatever that means. But why is it written that way? I mean couldn't you do something like some kind
of ClyBuilder and passing in the kind of what you want to be built?"

Anyway I think the general theme of this issue is perceived understandability by the people who may want to contribute to a project. If it's not understandable lesser people may want to help.

Thanks for your time.

**Comment by dionisiydk** [comment]
About 2):
Did you read class comment? How you will name it?

**Comment by dionisiydk** [comment]
about 1):
Idea was to create real hierarchy of classes in different packages with different combination of properties (extensions, traits, etc). It is not easy to produce short names for them. So they are in the state you see. You can suggest better names.

Normally you need to look at tests in Calypso-Environment-System-Tests package. Other packages (with extra suffixes) are for testing environment.

**Comment by Phantasus** [comment]
@dionisiydk Regarding 1) a small sidenote: This is a chicken and egg causality problem.
You are asking me who has the problem of "suffering" from the long names of
packages/classes to come up with a better name convention as if I understand
the code which you wrote as clear as you do.

Well I can try, but I don't think I understand your code well enough to come up with good
names.

As far as I understand Calypso you tried to make it extremly modular, because as 
a response to old Nautilus Browser monolithic infrastructure which was hard to extend.
And judging from your blogposts you build the Commander library as a base for
different commands which are used within Calypso to trigger actions. Which in the
end has the advantage of implementing remote browsing of remote Pharo images.
That's all my knowledge about it.

So based on that:
1. Calypso-Environment-System-Tests -> Calypso-SystemExtension-Tests

2. Calypso-Environment-System-Tests-P2WithSubclassFromP1 -> Calypso-SystemExtension-Tests, so just unifying it with Calypso-SystemExtension-Tests as the name doesn't make any sense to me.

3. Calypso-Environment-System-Tests-PExtendingTrait -> Calypso-SystemExtension-Tests also just unifying it with Calypso-SystemExtension-Tests as this name makes a little more sense to me without understanding the remaining software components.

4. ClySubclassWithTraitsOfClassWithTraits the only way what I can adhoc come up with, without understanding your code is not another name but some codesnippet as this is a little more readable to me and maybe other people too? Which is 
```query := ClyClass subclassOf: (ClyClass withTraits) withTraits. ``` as I suspect that this class is used in some queries within Calypso.

It's not a solution but this is what I can come up without knowing anything about your code.

**Comment by dionisiydk** [comment]
I will try to explain better :)
As I write purpose of packages with prefix "Calypso-Environment-System-Tests**-**" is to provide real system environment to test calypso queries. For example P5WithTags allows to test class queries over class tags.
To prepare this package I opened old browser and just create classes which I expect to query in tests. And old browser shows me what my calypso queries should return (because old browser works).
Then I wrote tests which query classes over this package and particular tags. If at some point these tests are failed I am able to just open old working browser to see test case in live and remember what it should be in Calypso.
Another example in short: P1WithHierarchy, P2WithSubclassFromP1 and P2WithSubclassFromP2.
I need to test ClyHierarchicallySortedClasses - how hierarchy will looks
- in single package,
- in two packages (when two packages selected) when they have no shared superclasses,
- in two packages when last one uses superclasses of first one
- in two packages when last one uses superclasses which not exist in first one but they share some deep root classes.

So with these packages (classes and methods) I am tried to model environment which describes all possible cases for calypso queries.

Is it now clear?

**Comment by dionisiydk** [comment]
And Calypso-SystemExtension is not correct. 
I have domain package Calypso-Environment-System. It is not about system extensions. It is about Calypso model of system environment.
And Calypso-Environment-System-Tests just follows package name convension where we just add Tests suffix to package under test.

**Comment by Phantasus** [comment]
No, I don't think I understand. I think I understood that you put every combination of calypso queries
into Classnames. And you explained to me some naming conventions you used for specific classes.

That didn't resolve my bewilderment. Then you explained that you seem to have come up with
this way, because it seems in an unknown way to promote incremental development of the
calypso browser as you wrote:

> To prepare this package I opened old browser and just create classes which I expect to query in tests. 
> And old browser shows me what my calypso queries should return (because old browser works).
> Then I wrote tests which query classes over this package and particular tags. If at some point these 
> tests are failed I am able to just open old working browser to see test case in live and remember 
> what it should be in Calypso.

This too didn't resolve my bewilderment. It seems like a tree traversal problem to me. So putting everything into ```ClyNode``` and then querying that?

Anyway I don't think I can contribute anything. Except my bewilderment and to some degree my
frustration. And as you are the main developer, hammering on this browser for some time I think
I leave it that way. As I think reacting to my "critique" is to some degree painful and people actually
want a browser which is remote browsing ready.

Thank you for your time.

**Comment by dionisiydk** [comment]
Just little note:

Alternative to my approach is to create required packages and classes just in tests. Problem that it will be quite complex setup in many cases. And it will lead to duplication in setup and tests which will need to be solved somehow. But then it will be very difficult to analyze test environment for particular test case.
With my approach I have real environment (real packages and classes) which is reusable by itself. And when you see in broken test that it queries Class1 and Class2 and expect some result you can just open working Nautilus browser and Calypso browser and analyze business case in live.

**Comment by dionisiydk** [comment]
And another note:

Discussed packages are about queries. But I don't thing you will need contribute to them. There is still few missing queries but I think main contribution should go to browser UI part itself. There are many things to do and many ideas. You probably read existing issues which mostly about what would be nice to have. So you can try to implement them. 
Also simplest contribution is to implement missing commands which exists in Nautilus.
Look at [presentation](http://dionisiydk.blogspot.fr/2017/05/pharodays2017-calypso-presentation.html) from PharoDays. It shows examples how implement these things.
