### ISSUE TITLE
Class definition tab not properly refreshed when instvar created from method

### ISSUE THREAD

**Issue by petr-fischer** [dionisiydk/Calypso#64]
How to reproduce:

1) click on class in browser
2) click on "new inst. method" tab and write new method, which reference nonexistent variable
3) save method
4) "unknown variable" selection dialog occurs
5) select "declare new instance variable" in this dialog
6) click on the middle tab (class definition tab) and look at class definition - generated instance variable is missing - this tab is not refreshed, you need to deselect class in the browser and select it again, then, class definition is OK

**Comment by dionisiydk** [comment]
Fixed in 0.8
