### ISSUE TITLE
Error when browsing class with class critique

### ISSUE THREAD

**Issue by marianopeck** [dionisiydk/Calypso#72]
I have a class with this definition:

        Object subclass: #DpSecurityPriceServer
	instanceVariableNames: ''
	classVariableNames: 'yahoo'
	package: 'DP-SecurityPrices'

When opening Calypso on this class, the method `resolvePropertiesOfCritique:` is called and `anEnvironmentItem` is:

         "a ClyEnvironmentItem([yahoo] Class (or pool) variable not capitalized)"

However, when you do "anchor interval" it ends up calling `searchString` which wrongly checks on instance side variables when in this case, it was class side variable. So the code:

        searchString
	^ sourceEntity instVarNames last = super searchString
		ifTrue:  [ super searchString, '''' ]
		ifFalse:	[ super searchString, ' ' ]

Gives error because `sourceEntity instVarNames` gives empty array so you can't send `last`.

---------------------------

Array(Object)>>errorSubscriptBounds:
Array(Object)>>at:
Array(SequenceableCollection)>>last
ReVarSearchSourceAnchor>>searchString
ReVarSearchSourceAnchor(ReSearchStringSourceAnchor)>>interval
ReVarSearchSourceAnchor>>interval
ClyCriticEnvironmentPlugin>>resolvePropertiesOfCritique:
ClyCritiqueScope class>>resolvePropertiesOf:by:
ClySortedCritiques(ClyEnvironmentContent)>>resolvePropertiesOf:by:
[ :each | anEnvironmentContent resolvePropertiesOf: anEnvironmentItem by: each ] in ClySystemNavigationEnvironment(ClyNavigationEnvironment)>>resolveItem:of: in Block: [ :each | anEnvironmentContent resolvePropertiesOf...etc...
OrderedCollection>>do:
ClySystemNavigationEnvironment(ClyNavigationEnvironment)>>resolveItem:of:
[ :each | environment resolveItem: each of: self ] in ClySortedCritiques(ClyEnvironmentContent)>>resolveItemsStartingAt:count: in Block: [ :each | environment resolveItem: each of: self ]...etc...
OrderedCollection>>do:
ClySortedCritiques(ClyEnvironmentContent)>>resolveItemsStartingAt:count:
ClyEnvironmentContentCache>>fillItemsFrom:
ClyEnvironmentContentCache class>>filledBy:startingAt:size:
ClySortedCritiques(ClyEnvironmentContent)>>createUpdateWithItemsStartingAt:count:
ClyEnvironmentContentCache>>createFullUpdateOf:
ClyEnvironmentCursor>>updateItemCache
ClyCollapsedDataSource(ClyDataSource)>>updateItems
ClyCollapsedDataSource(ClyDataSource)>>environmentChanged:
MessageSend>>value:
MessageSend>>cull:
MessageSend>>cull:cull:
[ action cull: anAnnouncement cull: announcer ] in AnnouncementSubscription>>deliver: in Block: [ action cull: anAnnouncement cull: announcer ]
BlockClosure>>on:do:
[ Processor terminateActive ] in [ :ex | 
| copy onDoCtx process handler bottom thisCtx |
onDoCtx := thisContext.
thisCtx := onDoCtx home.

"find the context on stack for which this method's is sender"
[ onDoCtx sender == thisCtx ]
	whileFalse: [ onDoCtx := onDoCtx sender.
		onDoCtx
			ifNil: [ "Can't find our home context. seems like we're already forked
				and handling another exception in new thread. In this case, just pass it through handler." ^ handlerAction cull: ex ] ].
bottom := [ Processor terminateActive ] asContext.
onDoCtx privSender: bottom.
handler := [ handlerAction cull: ex ] asContext.
handler privSender: thisContext sender.
(Process forContext: handler priority: Processor activePriority)
	resume.

"cut the stack of current process"
thisContext privSender: thisCtx.
nil ] in BlockClosure>>on:fork: in Block: [ Processor terminateActive ]

**Comment by dionisiydk** [comment]
Interesting why Nautilus works fine. 
Also interesting that error not happens when class var starts with uppercase letter

**Comment by dionisiydk** [comment]
It is issue of Renraku. It is not shown in Nautilus because this feature is not used.
What you can do is:
- remove method ReVarSearchSourceAnchor>>#searchString. I ask Yuriy about logic behind it. But it looks like useless.
- follow classic class var convention when first letter is uppercased 
If it is really important I of course can put try/catch on place where I use it.

**Comment by marianopeck** [comment]
Hi @dionisiydk 

Thanks for looking into. Sure, I can remove `ReVarSearchSourceAnchor>>#searchString` and I confirm it fixes it. And yeah, I can modify the code so that to do the recommendations that the critique says....BUT...if I cannot even open the browser to fix it ... Sure, I can workaround this too, but what I am saying is that we cannot NOT open the browser in these cases... So we need a solution. 

As said, the workaround of removing searchString does work. Let's see what Yuriy has to say...

Keep me informed!

Thanks a lot.

**Comment by dionisiydk** [comment]
Hmm, in my scenario browser opens fine. But it shows debugger. In fact critiques computed in background which should not break browser UI process

**Comment by dionisiydk** [comment]
From Yuriy about this space logic at the end:
> For example if you search for an instance variable called amp in a class called Example it will not find the variable but will highlight a part of the class name.
He will fix it but it is for Pharo 7. And anyway this interval not used in class definition.

**Comment by marianopeck** [comment]
Hi @dionisiydk 

It is not clear to me Yuriy answer... does  that mean that removing `ReVarSearchSourceAnchor>>#searchString` is safe enough or there is a better workaround? Sorry, but I must stay at 6.0.

And yes, sorry you are right, the browser is opened, but a debugger opens too.

**Comment by dionisiydk** [comment]
It is safe enough.

About Pharo 6. Is this issue critical for you? because if you will not create lowercase class vars (which we usually not do) then you will not see this bug

**Comment by dionisiydk** [comment]
So close issue  if it is ok

**Comment by marianopeck** [comment]
Thanks @dionisiydk.
